### ISSUE TITLE
Duvidas: slice dinamico

### ISSUE THREAD

**Issue by marioidival** [rust-br/estudos#11]
Eu tenho muito isso de criar coisas dinamicamente e sei que Rust não é uma linguagem dinamica 😬 , mas gostaria de saber se tem como eu criar um `slice` desse aqui (abaixo) dinamicamente.

```rust
&[&1i32, &"biz"] 
```

A ideia é que eu venha com um array de string, iterar sobre ele e da um `parser` nos valores, transformando os itens que podem ser transformados para um int.

Eu quero fazer umas queries no banco, mas ela é construida dinamicamente. Tive um problema com o `rust-postgres`, pois se eu tiver uma coluna do tipo int, eu não consigo passar para query uma string `"7"`, por exemplo...

Pra conseguir, eu fiz esse pequeno workaround:

https://github.com/marioidival/goga/blob/master/src/postgresql/commands.rs#L80-L86

_As libs de Go resolvem isso haha_

ref: https://github.com/sfackler/rust-postgres#querying

**Comment by leoyvens** [comment]
Olá Mario, não entendi a sua dúvida, você poderia fazer um [exemplo mínimo](http://sscce.org/) do que você quer e mandar no play ou postar aqui?

Uma dica não relacionada, você pode trocar esse código:
```rust
let operator = match query_operator(value_splited[0]) {
                        Ok(op) => op,
                        Err(e) => return Err(e),
};
```
Por simplesmente:
```rust
let operator = query_operator(value_splited[0])?;
```

**Comment by marioidival** [comment]
Claro @leodasvacas , só para você entender, vou explicar um pouco sobre o [goga](https://github.com/marioidival/goga).

A responsabilidade do goga é simplesmente fornecer uma maneira de acessar um banco de dados postgresql via REST.
Sem muitas configurações, apenas passando a [URL DO BANCO](https://github.com/marioidival/goga/blob/master/src/postgresql/connection.rs#L38), podemos acessar as tabelas.

Eu uso o [rust-postgresql](https://github.com/sfackler/rust-postgres).
# Meu problema:
Como eu sei acessar as tabelas, posso fazer [queries](https://github.com/sfackler/rust-postgres#querying) para retornar dados.
Essas queries são montadas por meio de [querystrings](https://github.com/marioidival/goga/blob/master/src/postgresql/commands.rs#L187-L525).

Baseado nessas informações, eu posso ja mostrar o codigo onde eu dou um `GET` em uma tabela e retornar dados.

https://github.com/marioidival/goga/blob/master/src/api/tables.rs#L33-L59

Aqui, eu vejo se o request vem com informações para montar um `WHERE, SELECT ou ORDER BY` e preparo a query. Pensando em ser dinamico, no momento do WHERE - exclusivamente nesse codigo - eu só consigo fazer a query com um valor:

[techo](https://github.com/marioidival/goga/blob/master/src/api/tables.rs#L56)
```
GET localhosj:8000/database/public/table?name=joao
# Gera algo como
SELECT * FROM database.public.table WHERE name=$1
e tenho um vetor com uma String "joao".
```

Mas, se acontecer algo diferente, como um `WHERE` com mais testes, não vou conseguir adicionar todos os valores:

```
GET localhosj:8000/database/public/table?name=joao&age=23
# Gera algo como
SELECT * FROM database.public.table WHERE name=$1 AND age=$2
e tenho um vetor com duas Strings "joao" e "23".
```
O [rust-postgres](https://github.com/sfackler/rust-postgres#querying) aceita no segundo argumento da função `query` um slice de referencias.

Então minha duvida é de como criar esse slice de referencias usando os valores vindo [daqui](https://github.com/marioidival/goga/blob/master/src/api/tables.rs#L41). [struct](https://github.com/marioidival/goga/blob/master/src/postgresql/commands.rs#L7-L9)

**Comment by leoyvens** [comment]
Você esbarrou no que é essencialmente o único motivo para existirem trait objects em Rust: coleções heterogêneas, ou seja, um vetor com valores de tipos diferentes.

Considerando que de algum modo você consegue divinar o tipo da coluna, aproveite o trait `ToSql` do rust-postgres e transforme seus valores em trait objects:

```rust
fn sequelize_values(values: Vec<String>) -> Vec<Box<ToSql>> {
  let sequelized: Vec<Box<ToSql>> = Vec::new();
  for value in values {
      /// `tipo` é o seu oráculo de tipos que retorna um enum de tipos.
      match tipo(value) {
        Str => sequelized.push(Box::new(value)),
        I32 => sequelized.push(Box::new(i32::from_str(value))),
        Bool => sequelized.push(Box::new(bool::from_str(value))),
        _ => unimplemented!()
     }
  }
  sequelized
}
```
Tendo isso você vai basicamente conseguir fazer:
```rust
connection.query("your_query_string", &sequelize_values(your_values));
```

**Comment by marioidival** [comment]
old but gold.
