### ISSUE TITLE
Proximo encontro: 12/09/2017

### ISSUE THREAD

**Issue by marioidival** [rust-br/estudos#4]
https://www.youtube.com/watch?v=8flK7h5kGBA

**Comment by rochacbruno** [comment]
https://gist.github.com/anonymous/a37eac0ac83368dc6d0cd575f02a22b9

PLAY: https://play.rust-lang.org/?gist=a37eac0ac83368dc6d0cd575f02a22b9&version=stable

**Comment by marioidival** [comment]
Links:

[functional wtih numbers and strings](https://play.rust-lang.org/?gist=32eb95d2b7367c6d30125ca963ee6fbf&version=stable
)

http://blog.madhukaraphatak.com/functional-programming-in-rust-part-1/
http://blog.madhukaraphatak.com/functional-programming-in-rust-part-2/

http://science.raphael.poss.name/rust-for-functional-programmers.html
https://mmstick.gitbooks.io/rust-programming-phoronix-reader-how-to/content/chapter02.html

update

**Comment by marioidival** [comment]
Exemplo do dia: 
https://play.rust-lang.org/?gist=16c67d70655b397dd1263f6681d80915&version=stable
